name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}    
    runs-on: ubuntu-latest
    
    steps:
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Retrieve keyvault secrets
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: "CodingSecrets"
        secrets: 'learn-terraform-backend-key'
      id: backendKey
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Transform
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_version: latest
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform init
      run: terraform init
      env:
        ARM_ACCESS_KEY: ${{steps.backendKey.learn-terraform-backend-key}}
    - name: Terraform Validate
      run: terraform validate -no-color
    - name: Terraform plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color -input=false
      continue-on-error: true
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
